<?php

/*
 * Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types=1);

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_highlight_library_info_build(): array {
  $highlight_library = ckeditor5_plugin_pack_library_loader(['highlight']);
  $styles = ckeditor5_plugin_pack_highlight_build_style_library();
  return array_merge($highlight_library, $styles);
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_highlight_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

function ckeditor5_plugin_pack_highlight_build_style_library(): array {
  $editors = \Drupal::entityTypeManager()->getStorage('editor')->loadMultiple();
  $libraries = [];
  foreach ($editors as $editor) {
    if ($editor->getEditor() !== 'ckeditor5') {
      continue;
    }

    $settings = $editor->getSettings();

    if (isset($settings["plugins"]["ckeditor5_plugin_pack_highlight__highlight"]) && isset($settings["plugins"]["ckeditor5_plugin_pack_highlight__highlight"]["attach_styles"]) && $settings["plugins"]["ckeditor5_plugin_pack_highlight__highlight"]["attach_styles"]) {
      $format = $editor->getFilterFormat()->id();
      $filename = 'ckeditor5_plugin_pack_highlight-' . $format . '.css';
      $key = 'highlight_styles.' . $format;
      $libraries[$key] = [
        'css' => [
          'theme' => [
            'public://ckeditor5/' . $filename => []
          ],
        ],
      ];
    }
  }
  return $libraries;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ckeditor5_plugin_pack_highlight_preprocess_page(&$variables) {
  $libraries = \Drupal::service('library.discovery')->getLibrariesByExtension('ckeditor5_plugin_pack_highlight');
  foreach ($libraries as $key => $library) {
    if (str_contains($key, 'highlight_styles')) {
      $variables['#attached']['library'][] = 'ckeditor5_plugin_pack_highlight/' . $key;
    }
  }
}
