<?php

/**
 * @file
 * Primary module hooks for CKEditor 5 Premium Features: Source Editing Enhanced module.
 */

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_source_editing_enhanced_library_info_build(): array {
  $definitions = [];
  if (\Drupal::service('ckeditor5_premium_features.core_library_version_checker')->isLibraryVersionHigherOrEqual('44.2.0')) {
    /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
    $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

    $definition = new LibraryDefinitionItem('source-editing-enhanced', $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }
  return $definitions;
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_premium_features_source_editing_enhanced_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  // Do not load plugin if CKEditor version doesn't support it.
  if (!\Drupal::service('ckeditor5_premium_features.core_library_version_checker')->isLibraryVersionHigherOrEqual('44.2.0')) {
    unset($plugin_definitions["ckeditor5_premium_features_source_editing_enhanced__source_editing_enhanced"]);
  }
}
