<?php

/*
 * Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types = 1);

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_templates_library_info_build(): array {
  return ckeditor5_plugin_pack_library_loader(['template']);
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_templates_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_plugin_pack_templates_library_info_alter(&$libraries, $extension): void {
  if ($extension === 'core' && isset($libraries['ckeditor5'])) {
    if (version_compare($libraries['ckeditor5']['version'], '44.0.0') >= 0) {
      $libraries['ckeditor5']['dependencies'][] = 'ckeditor5_plugin_pack_templates/distribution-channel';
    }
  }
}
