name: iied-main
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: a70da4cc-a976-4f36-999d-94e46d72df37
  ah_site_group: irforum
  php: '8.1'
services:
  appserver:
    webroot: docroot
    xdebug: true
    config:
      php: .vscode/php.ini
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/docroot'
        DRUSH_OPTIONS_URI: 'https://iied-main.lndo.site'
        # Support debugging Drush with XDEBUG. Use lando drush to debug.
        PHP_IDE_CONFIG: "serverName=localhost"
      volumes:
        - ../iied-d7/docroot/:/app/d7-files
    build_as_root:
      - apt update && apt install libgmp-dev -y && docker-php-ext-install gmp
  d7db:
    type: mysql
    creds:
      user: database
      password: database
      database: database
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: '/bin/s6-svscan /etc/services.d'
    portforward: true
  node:
    type: node:16
    ssl: true
    # command: cd /app/docroot/themes/custom/iied_tw && npm run watch
    port: 80
    overrides:
     ports:
      - 3000:3000
      - 3001:3001
  solr:
    type: solr:7
    portforward: false
    core: lando
    config:
      dir: lando/solr
proxy:
  adminer:
    - adminer.iied-main.lndo.site
  node:
    - bs.iied-main.lndo.site:3000
  solr:
  - solr.iied-main.lndo.site:8983
tooling:
  npm:
    service: node
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
  fix-imagick:
    service: appserver
    description: Update Imagick policy for PDF
    cmd: sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
    user: root