---
language: php

os: linux
dist: bionic

version: ~> 1.0

php: "7.3"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.rvm"
    - "${TMPDIR:-/tmp}/phpstan/cache"

env:
  global:
    - ORCA_SUT_NAME=drupal/acquia_search_solr
    - ORCA_SUT_BRANCH=3.x
    - ORCA_VERSION=^3
    - ORCA_PACKAGES_CONFIG_ALTER=../acquia_search_solr/tests/packages_alter.yml
    - ORCA_TELEMETRY_ENABLE=TRUE

jobs:
  fast_finish: true
  include:
    ## Only check for linting as this module is functionally not installable anymore.
    - { env: ORCA_JOB=STATIC_CODE_ANALYSIS, name: "Static code analysis" }

before_install:
  - composer create-project --no-dev acquia/orca ../orca "$ORCA_VERSION"
  - ../orca/bin/travis/before_install.sh

install: ../orca/bin/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script: ../orca/bin/travis/script.sh

before_cache: ../orca/bin/travis/before_cache.sh

after_success: ../orca/bin/travis/after_success.sh

after_failure: ../orca/bin/travis/after_failure.sh

after_script: ../orca/bin/travis/after_script.sh
