<?php

/**
 * @file
 * Module file for the Password Policy Password Separate Form module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure that our hooks are called AFTER Password Policy ones.
 */
function password_policy_change_pwd_page_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook implementations to the end of the list.
    case 'form_change_pwd_form_alter':
    case 'form_alter':
      $implementation = $implementations['password_policy_change_pwd_page'];
      unset($implementations['password_policy_change_pwd_page']);
      $implementations['password_policy_change_pwd_page'] = $implementation;
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function password_policy_change_pwd_page_form_alter(array &$form, FormStateInterface $form_state) {
  // Do not remove.
  // Required for hook_form_change_pwd_form_alter correct execution ordering.
}

/**
 * Implements hook_form_FORM_ID_alter() for user_pass_reset().
 */
function password_policy_change_pwd_page_form_change_pwd_form_alter(&$form, FormStateInterface $form_state) {
  $user = \Drupal::routeMatch()->getParameter('user');
  if ($user && \Drupal::service('password_policy.validation_manager')->tableShouldBeVisible()) {
    _password_policy_extras_add_libraries_and_settings_to_form($form);
  }
}
