<?php

/**
 * @file
 * The better passwords module file.
 */

use ZxcvbnPhp\Zxcvbn;
use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_element_info_alter().
 */
function better_passwords_element_info_alter(array &$info) {
  if (isset($info['password_confirm'])) {
    $info['password_confirm']['#after_build'][] = 'better_passwords_after_build';
  }
}

/**
 * After build function for password_confirm elements.
 *
 * @param array $element
 *   The element being altered after build.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form_state object returned with the element.
 */
function better_passwords_after_build(array $element, FormStateInterface $form_state) {
  $config = \Drupal::config('better_passwords.settings');

  // Set extra info on password_confirm description.
  $element['#description'] .= '<br/>' . t(
    'Passwords must be at least @num characters.',
    ['@num' => $config->get('length')]
  );
  if (!empty($config->get('strength'))) {
    $element['#description'] .= '<br/>' . t('Passwords will be rated for their strength.');
  }

  // Hide the password fields if Better Passwords is generating passwords.
  if (($generate = $config->get('auto_generate')) && \Drupal::currentUser()->isAuthenticated() && ($form_state->getFormObject()->getFormId() == 'user_register_form')) {
    $element['#required'] = $element['pass1']['#required'] = $element['pass2']['#required'] = FALSE;
    if ($generate == 1) {
      $element['pass1']['#states']['visible']['#auto-generate-password'] = $element['pass2']['#states']['visible']['#auto-generate-password'] = ['checked' => FALSE];
      $element['auto_generate_password'] = [
        '#type' => 'checkbox',
        '#title' => t('Auto-generate password'),
        '#checked' => TRUE,
        '#attributes' => ['id' => 'auto-generate-password'],
        '#parents' => $element['#parents'],
        '#array_parents' => $element['#array_parents'],
      ];
    }
    else {
      $element['pass1']['#access'] = $element['pass2']['#access'] = FALSE;
    }
  }

  // Better Password validate should come before other validate functions.
  array_unshift($element['#element_validate'], 'better_passwords_validate');

  return $element;
}

/**
 * Element validate function for password_confirm elements.
 *
 * @param array $element
 *   The element being validated.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form_state object returned with the element.
 */
function better_passwords_validate(array $element, FormStateInterface $form_state) {
  $config = \Drupal::config('better_passwords.settings');

  $minLength = $config->get('length');
  $minStrength = $config->get('strength');
  $autoGenerate = $config->get('auto_generate');

  $value = $element['pass1']['#value'];

  if ($value === "") {
    if ($autoGenerate && \Drupal::currentUser()->isAuthenticated() && ($form_state->getFormObject()->getFormId() == 'user_register_form')) {
      $genpass = \Drupal::service('password_generator')->generate(64);
      $form_state->setValueForElement($element, ['pass1' => $genpass, 'pass2' => $genpass]);
    }
    return TRUE;
  }

  // Variable to hold errors in password.
  $matches = [];

  // Check length of password.
  if (strlen($value) < $minLength) {
    $matches[] = t('Passwords must be at least @num characters.', ['@num' => $minLength]);
  }

  // Check strength of password.
  if (!empty($minStrength)) {

    $userdata = [
      $form_state->get('name'),
      $form_state->get('mail'),
    ];

    $z = new Zxcvbn();
    $strength = $z->passwordStrength($value, $userdata);

    if ($strength['score'] < $minStrength) {
      foreach ($strength['sequence'] as $obj) {
        if (!empty($obj->pattern)) {
          $str = substr($value, $obj->begin, $obj->end + 1 - $obj->begin);
          if ($str === $value) {
            $matches[] = match ($obj->pattern) {
              'date' => t('Your password must not be a date'),
              'dictionary' => t('Your password must not match a common password'),
              'digit' => t('Your password must not be fully numeric'),
              'repeat' => t('Your password must not be repetitive'),
              'sequence' => t('Your password must not be sequential'),
              'spatial' => t('Your password must not be adjacent on the keyboard'),
              'year' => t('Your password must not be a year'),
            };
          }
          else {
            $matches[] = match ($obj->pattern) {
              'date' => t('%str is a date', ['%str' => $str]),
              'dictionary' => t('Part %str matches a common password', ['%str' => $str]),
              'digit' => t('%str is numeric', ['%str' => $str]),
              'repeat' => t('%str is repetitive', ['%str' => $str]),
              'sequence' => t('%str is sequential', ['%str' => $str]),
              'spatial' => t('%str is adjacent on the keyboard', ['%str' => $str]),
              'year' => t('%str is a year', ['%str' => $str]),
            };
          }
        }
      }
    }
  }

  if (!empty($matches)) {
    $error = new FormattableMarkup(
      t('Please choose a stronger password.') . '<ul><li>' . implode('</li><li>', $matches) . '</li></ul>', []
    );
    $form_state->setError($element, $error);
  }
}
