<?php

/**
 * @file
 * Installation functions for Better passwords module.
 */

use Drupal\user\Entity\Role;

/**
 * Grants the new better passwords permission to existing roles.
 */
function better_passwords_update_10001(): void {
  foreach (Role::loadMultiple() as $role) {
    if ($role->hasPermission('administer site configuration') && !$role->hasPermission('administer better passwords')) {
      $role->grantPermission('administer better passwords');
      $role->save();
    }
  }
}
