<?php

/*
 * Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types = 1);

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_premium_features_version_override_library_info_alter(&$libraries, $extension): void {
  if ($extension === 'core') {
    /**
     * @var \Drupal\ckeditor5_premium_features_version_override\Utility\OverrideHandler $overrideHandler
     */
    $overrideHandler = \Drupal::service('ckeditor5_premium_features_version_override.override_handler');
    if ($overrideHandler->isOverrideEnabled()) {
      $overrideHandler->handleOverride($libraries);
    }
  }
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_premium_features_version_override_ckeditor5_plugin_info_alter(array &$plugin_definitions) {
  $versionChecker = \Drupal::service('ckeditor5_premium_features.core_library_version_checker');
  $overrideHandler = \Drupal::service('ckeditor5_premium_features_version_override.override_handler');
  $isKeyRequired = $versionChecker->isLibraryVersionHigherOrEqual('44.0.0');
  if ($overrideHandler->isOverrideEnabled() && $isKeyRequired) {
    // CKEditor 5 version 44+ requires a license key. For non-commercial use, use 'GPL'.
    // Add the 'GPL' license key to the CKEditor 5 Essentials plugin since it is always enabled.
    $definition = $plugin_definitions['ckeditor5_essentials'];
    $defArray = $definition->toArray();
    $defArray['ckeditor5']['config']['licenseKey'] = 'GPL';
    $newDefinition = new \Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition($defArray);
    $plugin_definitions['ckeditor5_essentials'] = $newDefinition;
  }
}
