include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
#   SKIP_ESLINT: '1'
  OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1


composer (next major):
  variables:
    _LENIENT_ALLOW_LIST: "entity_usage"
