# Schema for the configuration files of the CKEditor 5 Import from Word module.
ckeditor5.plugin.ckeditor5_premium_features_import_word__import_word:
  type: mapping
  label: 'Import Word'
  mapping:
    upload_media:
      label: 'Upload images as Media'
      type: mapping
      mapping:
        enabled:
          type: boolean
          label: 'Enable image upload as Media.'
        media_bundle:
          type: string
          label: 'Media bundle'
        media_field_name:
          type: string
          label: 'Media field name'
        image_destination_dir:
          type: string
          label: 'Image destination directory'

ckeditor5_premium_features_import_word.settings:
  type: config_object
  label: 'CKEditor 5 Import from Word settings'
  mapping:
    word_styles:
      type: boolean
      label: "Word's styles"
