display:
  default:
    display_title: Default
    display_options:
      fields:
        type:
          label: Vrsta
        timestamp:
          label: Datum
        name:
          label: Korisnik
        link:
          label: Operacije
      exposed_form:
        options:
          submit_button: Filter
      filters:
        type:
          expose:
            label: Vrsta
