password_policy_extras.settings:
  type: config_object
  label: 'Password Policy Extras config'
  mapping:
    disable_ajax_progress:
      type: boolean
      label: 'Disable Ajax throbber if true'
    failed_messages_only:
      type: boolean
      label: 'Only displays failed messages if true'
    hide_password_suggestions:
      type: boolean
      label: 'Hide default Drupal password suggestions if true'
    display_status_after_pass:
      type: boolean
      label: 'Move status display below the main password field if true'
    display_status_on_focus:
      type: boolean
      label: 'Display status table when password field has focus if true'
    status_refresh_delay:
      type: integer
      label: 'Status refresh delay in milliseconds'
