<?php

/**
 * @file
 * Primary module hooks for session_management module.
 */

/**
 * Implements hook_form_alter() to add IP restriction validation to login form.
 */
function session_management_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['#validate'][] = 'session_management_validate_ip_restriction';
  }
}

/**
 * Implements hook_user_login() for Saving the http user agent.
 */
function session_management_user_login($account) {
    $request = \Drupal::request();
    $current_session = $request->getSession();
    $current_session->set('mo_browser', $_SERVER['HTTP_USER_AGENT'] ?? 'Not Found');
}

/**
 * Validates IP restriction on login form.
 */
function session_management_validate_ip_restriction(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $config = \Drupal::config('session_management.settings');
  $mo_login_restriction = \Drupal::service('mo_login_restriction');
  $ip_login_restriction = $config->get('ip_login_restriction');
  $request = \Drupal::request();
  
  if ($ip_login_restriction && !$mo_login_restriction->isIpAllowedForLogin($request->getClientIp())) {
    $ip_message = $config->get('ip_message') ?? 'Your IP address is not allowed to login.';
    $form_state->setErrorByName('name', $ip_message);
  }
}

/**
 * Implements hook_menu_local_tasks_alter() for Sessions tab.
 */
function session_management_menu_local_tasks_alter(&$data, $route_name, &$cacheability) {

  $config = \Drupal::config('session_management.settings');

  if (!$config->get('enable_session_monitor')) {
    unset($data['tabs'][0]['session_management.session_manage']);
    $cacheability->addCacheTags(['user.permissions']);
  }

}

function session_management_page_attachments_alter(array &$attachment)
{
    $config = \Drupal::config('session_management.settings');

    if($config->get('autologout_enabled') && \Drupal::currentUser()->isAuthenticated()){

        $settings = [];
        $fields = [
            'autologout_enabled',
            'autologout_timeout',
            'autologout_response_time',
            'force_logout',
            'mo_modal_width',
            'mo_modal_title',
            'mo_modal_message',
            'mo_modal_yes_button_text',
            'mo_modal_no_button_text',
            'redirect_after_logout',
        ];

        foreach ($fields as $field){
            $settings[$field] = $config->get($field);
        }

        session_management_attach_js($attachment,$settings);
    }
}

    function session_management_attach_js(array &$element, array $settings): void
    {
        $element['#attached']['drupalSettings']['session_management'] = $settings;
        $element['#attached']['library'][] = 'session_management/session_management.mo_logout';
        $element['#cache']['tags'][] = 'config:session_management.settings';
    }