display:
  default:
    display_options:
      fields:
        type:
          label: Tipo
        timestamp:
          label: Data
        name:
          label: Usuário
        link:
          label: Operações
      filters:
        type:
          expose:
            label: Tipo
