<?php

/**
 * @file
 * Install and update hooks for the Read Only Mode module.
 */

use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 */
function readonlymode_install() {
  // Set the module weight to run as last.
  module_set_weight('readonlymode', 9999);
}

/**
 * Move the Read Only Mode settings from variable to config.
 */
function readonlymode_update_8001() {
  // Nothing to do.
}

/**
 * Set user permissions.
 */
function readonlymode_update_8002() {
  foreach (['anonymous', 'authenticated'] as $item) {
    if ($role = Role::load($item)) {
      $role->grantPermission('readonlymode access messages');
      $role->save();
    }
  }
}
