<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('variable', array(
  'fields' => array(
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'value' => array(
      'type' => 'blob',
      'not null' => TRUE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'name',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('variable')
->fields(array(
  'name',
  'value',
))
->values(array(
  'name' => 'linkchecker_scan_comment_article',
  'value' => 'i:1;',
))
->values(array(
  'name' => 'linkchecker_scan_comment_page',
  'value' => 'i:1;',
))
->values(array(
  'name' => 'linkchecker_scan_node_article',
  'value' => 'i:1;',
))
->values(array(
  'name' => 'linkchecker_scan_node_page',
  'value' => 'i:1;',
))
->execute();
