id: d7_acquia_connector_settings
label: 'Acquia Connector Settings'
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: acquia_connector_settings_v3
  variables:
    - acquia_agent_debug
    - acquia_spi_cron_interval
    - acquia_spi_cron_interval_override
    - acquia_agent_hide_signup_messages
  source_module: acquia_agent
process:
  debug: acquia_agent_debug
  cron_interval: acquia_spi_cron_interval
  cron_interval_override: acquia_spi_cron_interval_override
  hide_signup_messages: acquia_agent_hide_signup_messages
destination:
  plugin: config
  config_name: acquia_connector.settings
