id: d7_acquia_connector_settings_state
label: 'Acquia Connector Settings to State'
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: acquia_connector_settings_v4
  variables:
    - acquia_application_uuid
    - acquia_identifier
    - acquia_key
  source_module: acquia_agent
process:
  application_uuid: acquia_application_uuid
  identifier: acquia_identifier
  key: acquia_key
destination:
  plugin: state
  state_prefix: 'acquia_connector.'
