display:
  default:
    display_title: అప్రమేయం
    display_options:
      fields:
        type:
          label: రకం
        timestamp:
          label: తేదీ
        name:
          label: వాడుకరి
        link:
          label: కార్యాలు
      exposed_form:
        options:
          submit_button: Filter
      filters:
        type:
          expose:
            label: రకం
