<?php


/**
 * Implements hook_theme().
 */
function iied_filters_theme($existing, $type, $theme, $path) {

  return [
    'iied_filters_video_embed_code' => [
      'template' => 'iied-filters-video-embed-code',
      'variables' => [
        'url' => NULL,
        'style' => 'normal',
        'video_data' => [],
      ],
    ],
  ];



}

/**
 * Processes variables to format a video player.
 *
 * @param array $variables
 *   Contains the following information:
 *    - $url
 *    - $style
 *    - $video_data
 */
function template_preprocess_iied_filters_video_embed_code(&$variables) {
  // Get the handler.
  $handler = iied_filters_get_handler($variables['url']);
  $variables['handler'] = $handler['name'];

  // Load the style.
  $style = video_embed_field_video_style_load($variables['style']);
  // If there was an issue load in the default style.
  if ($style == FALSE) {
    $style = video_embed_field_video_style_load('normal');
  }
  if (isset($style->data[$variables['handler']])) {
    $variables['style_settings'] = $style->data[$variables['handler']];
  }
  // Safety value for when we add new handlers and there are styles stored.
  else {
    $variables['style_settings'] = $handler['defaults'];
  }

  // Prepare the URL.
  if (!stristr($variables['url'], 'http://') && !stristr($variables['url'], 'https://')) {
    $variables['url'] = 'http://' . $variables['url'];
  }

  // Prepare embed code.
  if ($handler && isset($handler['function']) && function_exists($handler['function'])) {
    $embed_code = call_user_func($handler['function'], $variables['url'], $variables['style_settings']);
    $variables['embed_code'] = drupal_render($embed_code);
  } else {
    $variables['embed_code'] = l($variables['url'], $variables['url']);
  }

  // Prepare video data.
  $variables['data'] = $variables['video_data'];
  unset($variables['video_data']);
}


/**
 * Retrieves the video handler for a video URL.
 *
 * @param string $url
 *   The video URL.
 *
 * @return string|bool
 *   The handler name for the URL, FALSE in case there is no handler.
 */
function iied_filters_get_handler($url) {
  // Process video URL.
  if (!stristr($url, 'http://') && !stristr($url, 'https://')) {
    $url = 'http://' . $url;
  }
  $parts = parse_url($url);
  if (!isset($parts['host'])) {
    return FALSE;
  }

  $host = $parts['host'];
  if (stripos($host, 'www.') > -1) {
    $host = substr($host, 4);
  }

  $domains = _video_embed_field_get_provider_domains();
  $handlers = video_embed_get_handlers();
  if (isset($domains[$host])) {
    $handler_name = $domains[$host];
    $handler = $handlers[$handler_name];
    $handler['name'] = $handler_name;
    return $handler;
  } else {
    return FALSE;
  }
}
