plugin.plugin_configuration.search_api_solr_connector.solr_acquia_connector:
  type: config_object
  label: 'Search API Solr solr_acquia_connector connector settings'
  mapping:
    scheme:
      type: string
      label: 'The HTTP protocol to use for sending queries'
    timeout:
      type: integer
      label: 'Timeout for search queries'
    index_timeout:
      type: integer
      label: 'Timeout for indexing requests'
    optimize_timeout:
      type: integer
      label: 'Timeout for optimize requests'
    finalize_timeout:
      type: integer
      label: 'Timeout for finalize requests'
    commit_within:
      type: integer
      label: 'Time until a soft commit has to happen'
    solr_version:
      type: string
      label: 'Solr version override'
    http_method:
      type: string
      label: 'The HTTP method to use for sending queries'
    jmx:
      type: boolean
      label: 'Enable JMX'
