id: d6_linkchecker_settings
label: Linkchecker 6 configuration
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: variable
  variables:
    - linkchecker_action_status_code_301
    - linkchecker_action_status_code_404
    - linkchecker_check_connections_max
    - linkchecker_check_library
    - linkchecker_check_links_interval
    - linkchecker_fqdn_only
    - linkchecker_check_useragent
    - linkchecker_disable_link_check_for_urls
    - linkchecker_extract_from_a
    - linkchecker_extract_from_audio
    - linkchecker_extract_from_embed
    - linkchecker_extract_from_iframe
    - linkchecker_extract_from_img
    - linkchecker_extract_from_object
    - linkchecker_extract_from_video
    - linkchecker_filter_blacklist
    - linkchecker_ignore_response_codes
    - linkchecker_impersonate_user
    - linkchecker_scan_blocks
    - linkchecker_log_level
  source_module: linkchecker
process:
  'scan_blocks': linkchecker_scan_blocks
  'check_links_types': linkchecker_fqdn_only
  'extract/from_a': linkchecker_extract_from_a
  'extract/from_audio': linkchecker_extract_from_audio
  'extract/from_embed': linkchecker_extract_from_embed
  'extract/from_iframe': linkchecker_extract_from_iframe
  'extract/from_img': linkchecker_extract_from_img
  'extract/from_object': linkchecker_extract_from_object
  'extract/from_video': linkchecker_extract_from_video
  'extract/filter_blacklist': linkchecker_filter_blacklist
  'check/connections_max': linkchecker_check_connections_max
  'check/disable_link_check_for_urls': linkchecker_disable_link_check_for_urls
  'check/library': linkchecker_check_library
  'check/interval': linkchecker_check_links_interval
  'check/useragent': linkchecker_check_useragent
  'error/action_status_code_301': linkchecker_action_status_code_301
  'error/action_status_code_404': linkchecker_action_status_code_404
  'error/ignore_response_codes': linkchecker_ignore_response_codes
  'error/impersonate_account': linkchecker_impersonate_user
  'logging/level': linkchecker_log_level
destination:
  plugin: config
  config_name: linkchecker.settings
