include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  SKIP_ESLINT: 1
  _PHPUNIT_CONCURRENT: 1
  OPT_IN_TEST_PREVIOUS_MINOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1

composer (previous major):
  after_script:
    - composer remove drupal/contact --dev
  variables:
    _LENIENT_ALLOW_LIST: "entity_reference_revisions, aggregator, tour, rdf, contact"
composer (previous minor):
  after_script:
    - composer remove drupal/contact --dev
  variables:
    _LENIENT_ALLOW_LIST: "entity_reference_revisions, aggregator, tour, rdf, contact"
composer (next major):
  variables:
    _LENIENT_ALLOW_LIST: "entity_reference_revisions, aggregator, tour, rdf, contact"

