<?php

/**
 * @file
 * Adds support for serializing entities to Hypertext Application Language.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\hal\Hook\HalHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function hal_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(HalHooks::class)->help($route_name, $route_match);
}
