views.filter.facets_filter:
  type: views_filter
  label: 'Facets filter'
  mapping:
    hierarchy:
      type: boolean
      label: 'Show hierarchy'
    label_display:
      type: string
    facet:
      type: mapping
      mapping:
        query_operator:
          type: string
          label: 'Query operator'
        min_count:
          type: integer
          label: 'Query operator'
        show_numbers:
          type: boolean
          label: 'Query operator'
        processor_configs:
          type: sequence
          label: 'Processor settings'
          sequence:
            type: mapping
            label: 'A processor'
            mapping:
              processor_id:
                type: string
                label: 'The plugin ID of the processor'
              weights:
                type: sequence
                label: 'The processor''s weights for the different processing stages'
                sequence:
                  type: integer
                  label: 'The processor''s weight for this stage'
              settings:
                type: plugin.plugin_configuration.facets_processor.[%parent.processor_id]
