const postcss = require('postcss');

module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: {
    enabled: process.env.production, // Set to false or true to manually toggle CSS purge
    mode: 'layers', // set to 'all' to purge your own CSS as well
    layers: ['base', 'components', 'utilities'],
    content: [ // Files to be scanned by purgecss
      './source/**/*.twig',
      './source/**/*.js',
      './templates/**/*.twig',
      './js/*.js'
    ],
    options: {
      whitelist: ['html', 'body'], // Array of whitelisted classes
      whitelistPatterns: [], // RegEx for whitelisted classes eg /^grid-*/
      keyframes: false, // Remove unused keyframes
      fontFace: false, // Remove unused fontface rules
    },
  },
  theme: {
    screens: {
      sm: '320px',
      md: '768px',
      lg: '1200px',
      xl: '1920px',
    },
    colors: {
      'white': 'white',
      'admin-dark': '#2d2d2d',
      'admin-light': '#434343',
      'admin-green': '#88B46D',
      'admin-red': '#BF6767',
      'admin-blue': '#60A3C0',
      'transparent': 'rgba(0,0,0,0)',
      'gray-light': '#F6F6F6',
      'gray-dark': '#7E7E7E',
      black: {
        default: '#101820',
        'mixed-white': '#26343c',
      },
      'colour-one': '#23334B',
      'colour-two': '#F35C49',
    },
    container: {
      center: true,
      padding: '1.5rem',
    },
    fontFamily: {
      body: ['Roboto', 'arial' ,'sans-serif'],
      mono: ['Inconsolata', 'consolas', 'menlo', 'courier', 'monospaced'],
    },
    fontSize: {
      'base': '1rem',
      '12': '0.75rem',
      '14': '0.875rem',
      '18': '1.125rem',
      '19': '1.1875rem',
      '20': '1.25rem',
      '21': '1.3125rem',
      '22': '1.375rem',
      '24': '1.5rem',
      '26': '1.625rem',
      '28': '1.75rem',
      '32': '2rem',
      '38': '2.375rem',
      '44': '2.75rem',
      '48': '3rem',
      '60': '3.75rem',
      '74': '4.625rem',
    },
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    lineHeight: {
      'base': '100%',
      '90': '90%',
      '95': '95%',
      '105': '105%',
      '110': '110%',
      '115': '115%',
      '120': '120%',
      '130': '130%',
      '145': '145%',
      '160': '160%',
    },
    letterSpacing: {
      '02': '-0.02em',
      '03': '-0.03em',
    },
    spacing: {
			px: '1px',
			'0': '0',
			'4': '0.25rem',
      '8': '0.5rem',
      '12': '0.75rem',
			'16': '1rem',
			'24': '1.5rem',
      '32': '2rem',
      '36': '2.25rem',
			'48': '3rem',
      '64': '4rem',
      '70': '4.375rem',
      '80': '5rem',
      '98': '6.125rem',
      '128': '8rem',
      '144': '9rem',
		},
    zIndex: {
      '-1': '-1',
      '0': 0,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
      'auto': 'auto',
    },
    flexGrow: {
      '0': 0,
      '1': 1,
      '2': 2,
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '3': '3px',
      '4': '4px',
      '5': '5px',
      '6': '6px',
      '8': '8px',
    },
    extend: {
      inset: {
        '1': '1rem',
        '2': '2rem',
        '3': '3rem',
        '4': '4rem',
        '10': '10rem',
      },
      fill: theme => ({
        'colour-one': theme('colors.colour-one'),
      }),
      transitionDuration: {
        '0': '0ms',
      },
    },
  },
  variants: {
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    flexDirection: ['responsive'],
    flexWrap: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    justifyContent: ['responsive'],
    alignContent: ['responsive'],
    flex: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    order: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    inset: ['responsive'],
    resize: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    fill: ['responsive'],
    stroke: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    fontSize: ['responsive'],
    fontStyle: ['responsive'],
    textTransform: ['responsive'],
    textDecoration: ['responsive', 'hover', 'focus'],
    fontSmoothing: ['responsive'],
    letterSpacing: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    wordBreak: ['responsive'],
    width: ['responsive'],
    zIndex: ['responsive'],
  },
  plugins: [
    function({ addUtilities }) {
      const backfaceVisibility = {
        '.backface-visibility-visible': {
          'backface-visibility': 'visible',
        },
        '.backface-visibility-hidden': {
          'backface-visibility': 'hidden',
        },
      }
      addUtilities(backfaceVisibility, ['responsive', 'hover'])
    },
  ]
}
