<?php

/**
 * @file
 * Install, update and uninstall functions for the Form Mode Control module.
 */

/**
 * Update the schema of form_mode_control.settings configuration.
 */
function form_mode_control_update_9001() {
  $config_factory = \Drupal::configFactory();
  $config_name = 'form_mode_control.settings';

  // Load the old configuration.
  $config = $config_factory->getEditable($config_name);

  // Get the current sequence values.
  $old_values = $config->get('sequence');

  // Transform old sequence values to new mapping structure.
  if (is_array($old_values)) {
    $new_values = [];
    foreach ($old_values as $value) {
      $new_values[] = ['config_value' => $value];
    }

    // Clear the old sequence and set the new mapping structure.
    $config->clear('sequence');
    $config->set('config_value', $new_values);
    $config->save();
  }
}

/**
 * Update the schema of form_mode_control.settings configuration.
 */
function form_mode_control_update_9002() {
  $config = \Drupal::configFactory()
    ->getEditable('form_mode_control.settings');

  $old_data = $config->getRawData();
  if (isset($old_data['form_modes'])) {
    return;
  }

  $new_data = [];
  if (isset($old_data['_core'])) {
    $new_data['_core'] = $old_data['_core'];
    unset($old_data['_core']);
  }
  if (isset($old_data['langcode'])) {
    $new_data['langcode'] = $old_data['langcode'];
    unset($old_data['langcode']);
  }
  $new_data['form_modes'] = $old_data;

  $config->setData($new_data);
  $config->save();
}

/**
 * Recalculate permission dependencies for form_mode_control.
 */
function form_mode_control_update_9003() {
  // Load all roles.
  $role_storage = \Drupal::entityTypeManager()->getStorage('user_role');
  $roles = $role_storage->loadMultiple();

  foreach ($roles as $role) {
    // Simply re-save the role to trigger permission dependency recalculation.
    $role->save();
  }
}

/**
 * Restructure config.
 */
function form_mode_control_update_9004(): string {
  $config = \Drupal::configFactory()
    ->getEditable('form_mode_control.settings');
  $data = $config->getRawData();

  if (!isset($data['form_modes'])) {
    return 'No restructuring needed.';
  }

  $defaults = [];
  foreach ($data['form_modes'] as $key => $value) {
    if (strpos($key, 'use  The form mode') === 0) {
      continue;
    }

    $keyParts = explode('+', $key);
    if (count($keyParts) === 4) {
      [$mode, $role] = $keyParts;
      if ($mode === 'creation') {
        $mode = 'create';
      }
      else {
        $mode = 'edit';
      }

      [$entityTypeId, $bundle, $formModeId] = explode('.', $value);

      if ($formModeId === 'default') {
        continue;
      }

      $defaults[$entityTypeId][$bundle][$mode][$role] = $formModeId;
    }
  }

  $config->clear('form_modes');
  $config->set('defaults', $defaults);
  $config->save();

  return 'Restructuring completed.';
}
