media_thumbnails.settings:
  type: config_object
  label: 'Media Thumbnails settings'
  mapping:
    bgcolor_active:
      type: boolean
      label: 'Use custom background color'
    bgcolor_value:
      type: string
      label: 'Background color hex value'
    width:
      type: integer
      label: 'Thumbnail width'
