display:
  default:
    display_title: Bawaan
    display_options:
      fields:
        type:
          label: Jenis
        timestamp:
          label: Tanggal
        name:
          label: Pengguna
        link:
          label: Operasi-operasi
      exposed_form:
        options:
          submit_button: Filter
      filters:
        type:
          expose:
            label: Jenis
