login_redirect_per_role.settings:
  type: config_object
  mapping:
    login:
      type: sequence
      label: 'Login redirect settings'
      sequence:
        type: login_redirect_per_role.item
    logout:
      type: sequence
      label: 'Logout redirect settings'
      sequence:
        type: login_redirect_per_role.item

login_redirect_per_role.item:
  type: mapping
  mapping:
    redirect_url:
      type: string
      label: 'Redirect URL'
    allow_destination:
      type: boolean
      label: 'Allow destination'
    weight:
      type: integer
      label: 'Allow destination'
