# Config schema for slider, you can find the implementation in
# Drupal\facets_range\Plugin\facets\widget\SliderWidget.
facet.widget.config.slider:
  type: facet.widget.default_config
  label: 'List of range widget configuration'
  mapping:
    prefix:
      type: label
      label: 'Prefix'
    suffix:
      type: label
      label: 'Suffix'
    min_type:
      type: string
      label: 'Minimum type'
    min_value:
      type: float
      label: 'Minimum value'
    max_type:
      type: string
      label: 'Maximum type'
    max_value:
      type: float
      label: 'Maximum value'
    step:
      type: float
      label: 'Step'

facet.widget.config.range_slider:
  type: facet.widget.default_config
  label: 'List of range widget configuration'
  mapping:
    prefix:
      type: label
      label: 'Prefix'
    suffix:
      type: label
      label: 'Suffix'
    min_type:
      type: string
      label: 'Minimum type'
    min_value:
      type: float
      label: 'Minimum value'
    max_type:
      type: string
      label: 'Maximum type'
    max_value:
      type: float
      label: 'Maximum value'
    step:
      type: float
      label: 'Step'

plugin.plugin_configuration.facets_processor.slider:
  type: mapping
  label: 'Slider'

plugin.plugin_configuration.facets_processor.range_slider:
  type: mapping
  label: 'Range slider'
