<?php

/*
 * Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types = 1);

use Drupal\ckeditor5_plugin_pack_word_count\Element\TextFormat;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_word_count_library_info_build(): array {
  return ckeditor5_plugin_pack_library_loader(['word-count']);
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_word_count_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}
