# Schema for the configuration files of the Content Translation Redirect module.

content_translation_redirect.entity.*:
  type: config_entity
  label: 'Content Translation Redirect'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    code:
      type: integer
      label: 'Redirect status'
    path:
      type: path
      label: 'Redirect path'
    translatable_entity_only:
      type: boolean
      label: 'Only act on translatable entities'
