<?php

/**
 * @file
 * Contains publishcontent.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function publishcontent_help($route_name, RouteMatchInterface $route_match): ?string {
  switch ($route_name) {
    case 'help.page.publishcontent':
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
        $output = '<pre>' . $readme . '</pre>';

        return $output;
      }
  }
  return NULL;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function publishcontent_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $config = Drupal::config('publishcontent.settings');

  if (isset($form['status']['widget']['value'])) {
    $form['status']['widget']['value']['#title'] = $config->get('publish_text_value');
    if (!array_key_exists('#default_value', $form['status']['widget']['value'])) {
      $form['status']['widget']['value']['#default_value'] = 0;
    }
    $form['status']['widget']['value']['#default_value'] ?
      $form['meta']['published']['#markup'] = $config->get('publish_markup_value') :
      $form['meta']['published']['#markup'] = $config->get('unpublish_markup_value');
    if (empty($config) || empty($config->get('ui_checkbox'))) {
      $form['status']['#disabled'] = TRUE;
      return;
    }
  }

  if (!empty($form['status']) && empty($form['status']['#access'])) {
    $user = Drupal::currentUser();
    $node = $form_state->getFormObject()->getEntity();
    /** @var \Drupal\publishcontent\Access\PublishContentAccess $publish_content_access */
    $publish_content_access = Drupal::service('publishcontent.access');
    $form['status']['#access'] = TRUE;

    if (!$publish_content_access->access($user, $node)->isAllowed()) {
      $form['status']['#disabled'] = TRUE;
      $form['status']['widget']['value']['#description'] = t('You can not change the @published status.', [
        '@published' => $config->get('publish_text_value'),
      ]);

      // If the user cannot publish content, they should not be allowed
      // to create published content.
      if ($node->isNew()) {
        $form['status']['widget']['value']['#default_value'] = 0;
      }
    }
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function publishcontent_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  // Publishcontent module logic only applies to nodes at the moment.
  if ($entity_form['#entity_type'] === 'node') {
    publishcontent_form_node_form_alter($entity_form, $form_state);
  }
}
